### ISSUE TITLE
Please rename the repo to something less generic than ZSH-Theme

### ISSUE THREAD

**Issue by unixorn** [gh05t-4/ZSH-Theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the repository name is awfully generic. Please consider renaming it to something more descriptive, or even just name it after your github username.

Thanks!

**Comment by gh05t-4** [comment]
Sorry for the very late reply, I've changed the repository name. Please check if it's feasible.

**Comment by gh05t-4** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but the repository name is awfully generic. Please consider renaming it to something more descriptive, or even just name it after your github username.
> 
> Thanks!

Sorry for the very late reply, I've changed the repository name. Please check if it's feasible.
